resources:
  products:
    entity: App\Entity\Product
    operations: [R, D, L, P]
    path: /products
    export: true
    requirements:
      id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS