resources:
  products:
    entity: App\Entity\Product
    operations: [R, D, L, P]
    path: /products
    export: true
    requirements:
      id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS

  users:
    entity: App\Entity\User
    operations: [ C, R, D, L, P ]
    path: /users
    requirements:
      id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    security:
      C: [ ROLE_ADMIN ]
      P: [ ROLE_ADMIN ]
      D: [ ROLE_ADMIN ]
      L: [ ROLE_ADMIN ]
      R: [ ROLE_ADMIN ]